### ISSUE TITLE
includePath doesnt work

### ISSUE THREAD

**Issue by sggpls** [ktnrg45/vs-code-cython#17]
Hello, I have a ton of headers in include directory with main .pxd header with imports and one main .pyx file. And extension doesnt see any thing inside main .pyx file and cant move to definition. Only if I move all headers to the root around main .pyx file. includePath option seems doesnt work.

**Comment by ktnrg45** [comment]
Hi, so just to clarify, is your directory structure like this?

root/main.pyx
root/include/main.pxd
root/include/other.pxd

**Comment by sggpls** [comment]
hello, yes, u r right.

**Comment by ktnrg45** [comment]
This should be fixed now.

**Comment by sggpls** [comment]
Sorry, may be i don't understand how to add it, but it still doesn't work. I added paths using Setting/Extentions/Cython/includePath inside IDE, tried create .vscode/pyrightconfig.json with includes, also tried reinstall package with edited package.json where i write inludePath by my hands - still not working...
